// Mock data for development — replace with Firestore queries once Firebase is connected

// ─── Athletes ────────────────────────────────────────────────
export const mockAthletes = [
  {
    id: '1',
    firstName: 'Marcus',
    lastName: 'Johnson',
    name: 'Marcus Johnson',
    dateOfBirth: new Date('2011-06-14'), // age 14
    gender: 'male' as const,
    position: 'Forward',
    positionShort: 'ST',
    teamName: 'FC Phoenix U15',
    league: 'Metro Youth League',
    jerseyNumber: 9,
    photoUrl: null,
    stats: { games: 22, goals: 18, assists: 7, minutes: 1680, yellowCards: 2, redCards: 0 },
  },
  {
    id: '2',
    firstName: 'Sofia',
    lastName: 'Martinez',
    name: 'Sofia Martinez',
    dateOfBirth: new Date('2013-03-22'), // age 12
    gender: 'female' as const,
    position: 'Midfielder',
    positionShort: 'CM',
    teamName: 'City Stars U13',
    league: 'Regional Academy',
    jerseyNumber: 8,
    photoUrl: null,
    stats: { games: 16, goals: 5, assists: 11, minutes: 1190, yellowCards: 0, redCards: 0 },
  },
  {
    id: '3',
    firstName: 'Liam',
    lastName: 'Chen',
    name: 'Liam Chen',
    dateOfBirth: new Date('2009-11-05'), // age 16
    gender: 'male' as const,
    position: 'Defender',
    positionShort: 'CB',
    teamName: 'United FC U17',
    league: 'State Development League',
    jerseyNumber: 5,
    photoUrl: null,
    stats: { games: 20, goals: 2, assists: 3, minutes: 1800, yellowCards: 3, redCards: 0 },
  },
  {
    id: '4',
    firstName: 'Amara',
    lastName: 'Osei',
    name: 'Amara Osei',
    dateOfBirth: new Date('2012-08-17'), // age 13
    gender: 'female' as const,
    position: 'Goalkeeper',
    positionShort: 'GK',
    teamName: 'City Stars U13',
    league: 'Regional Academy',
    jerseyNumber: 1,
    photoUrl: null,
    stats: { games: 16, goals: 0, assists: 0, minutes: 1440, yellowCards: 1, redCards: 0 },
  },
];

// ─── Games ────────────────────────────────────────────────────
export const mockGames = [
  {
    id: 'g1',
    athleteId: '1',
    date: new Date('2026-03-15'),
    opponent: 'River City FC',
    result: 'win' as const,
    score: { home: 3, away: 1 },
    goals: 2,
    assists: 1,
    minutesPlayed: 80,
    shots: 5,
    yellowCards: 0,
    redCards: 0,
    position: 'ST',
    notes: 'Hat-trick attempt, scored twice. Strong pressing game.',
    athleteName: 'Marcus Johnson',
    verified: true,
  },
  {
    id: 'g2',
    athleteId: '1',
    date: new Date('2026-03-08'),
    opponent: 'Blue Hawks',
    result: 'win' as const,
    score: { home: 2, away: 0 },
    goals: 1,
    assists: 0,
    minutesPlayed: 90,
    shots: 4,
    yellowCards: 0,
    redCards: 0,
    position: 'ST',
    notes: '',
    athleteName: 'Marcus Johnson',
    verified: true,
  },
  {
    id: 'g3',
    athleteId: '2',
    date: new Date('2026-03-08'),
    opponent: 'Sunset United',
    result: 'draw' as const,
    score: { home: 1, away: 1 },
    goals: 1,
    assists: 0,
    minutesPlayed: 75,
    shots: 2,
    yellowCards: 0,
    redCards: 0,
    position: 'CM',
    notes: 'Good performance in midfield.',
    athleteName: 'Sofia Martinez',
    verified: true,
  },
  {
    id: 'g4',
    athleteId: '1',
    date: new Date('2026-03-01'),
    opponent: 'North Stars',
    result: 'loss' as const,
    score: { home: 0, away: 2 },
    goals: 0,
    assists: 0,
    minutesPlayed: 60,
    shots: 1,
    yellowCards: 1,
    redCards: 0,
    position: 'ST',
    notes: 'Tough match, limited chances.',
    athleteName: 'Marcus Johnson',
    verified: false,
  },
  {
    id: 'g5',
    athleteId: '1',
    date: new Date('2026-02-22'),
    opponent: 'Valley SC',
    result: 'win' as const,
    score: { home: 4, away: 2 },
    goals: 3,
    assists: 0,
    minutesPlayed: 90,
    shots: 7,
    yellowCards: 0,
    redCards: 0,
    position: 'ST',
    notes: 'Outstanding game, hat-trick!',
    athleteName: 'Marcus Johnson',
    verified: true,
  },
  {
    id: 'g6',
    athleteId: '2',
    date: new Date('2026-02-15'),
    opponent: 'Oak Ridge FC',
    result: 'win' as const,
    score: { home: 3, away: 0 },
    goals: 0,
    assists: 2,
    minutesPlayed: 90,
    shots: 1,
    yellowCards: 0,
    redCards: 0,
    position: 'CM',
    notes: 'Two assists, great vision today.',
    athleteName: 'Sofia Martinez',
    verified: true,
  },
  {
    id: 'g7',
    athleteId: '3',
    date: new Date('2026-03-12'),
    opponent: 'Eastside Eagles',
    result: 'win' as const,
    score: { home: 2, away: 1 },
    goals: 1,
    assists: 0,
    minutesPlayed: 90,
    shots: 2,
    yellowCards: 0,
    redCards: 0,
    position: 'CB',
    notes: 'Scored a header from a corner.',
    athleteName: 'Liam Chen',
    verified: true,
  },
  {
    id: 'g8',
    athleteId: '4',
    date: new Date('2026-03-08'),
    opponent: 'Sunset United',
    result: 'draw' as const,
    score: { home: 1, away: 1 },
    goals: 0,
    assists: 0,
    minutesPlayed: 90,
    shots: 0,
    yellowCards: 0,
    redCards: 0,
    position: 'GK',
    notes: '4 saves, solid performance.',
    athleteName: 'Amara Osei',
    verified: true,
  },
];

// ─── Dashboard Summary ────────────────────────────────────────
export const mockDashboardStats = {
  totalGoals: 23,
  totalAssists: 12,
  gamesPlayed: 18,
  winRate: 78,
  goalsThisMonth: 5,
  assistsThisMonth: 2,
  gamesThisMonth: 4,
  winRateChange: 3,
};

// ─── Dream Gym Progress ───────────────────────────────────────
export const mockDreamGymProgress = {
  workoutsCompleted: 8,
  workoutsGoal: 12,
  practicesLogged: 5,
  practicesGoal: 8,
  mentalSessions: 3,
  mentalGoal: 4,
};

// ─── Positions ────────────────────────────────────────────────
export const POSITIONS = [
  { value: 'GK', label: 'Goalkeeper' },
  { value: 'CB', label: 'Center Back' },
  { value: 'LB', label: 'Left Back' },
  { value: 'RB', label: 'Right Back' },
  { value: 'CDM', label: 'Defensive Midfielder' },
  { value: 'CM', label: 'Central Midfielder' },
  { value: 'CAM', label: 'Attacking Midfielder' },
  { value: 'LW', label: 'Left Wing' },
  { value: 'RW', label: 'Right Wing' },
  { value: 'ST', label: 'Striker' },
  { value: 'CF', label: 'Center Forward' },
];

export const LEAGUES = [
  'Metro Youth League',
  'Regional Academy',
  'State Development League',
  'Club League',
  'School League',
  'Recreational',
  'Other',
];
