#!/bin/bash
# Fix GitHub Email Spam - Quick Setup Guide
# Run this to get direct links to fix notification settings

echo "════════════════════════════════════════════════════════════════"
echo "🔕 STOP GITHUB EMAIL SPAM - Configuration Links"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Follow these 3 steps to stop the email flood:"
echo ""
echo "1️⃣  DISABLE INDIVIDUAL DEPENDABOT EMAILS"
echo "   👉 https://github.com/settings/notifications"
echo ""
echo "   Actions:"
echo "   - Scroll to 'Dependabot alerts'"
echo "   - ✅ ENABLE 'Weekly digest' or 'Daily digest'"
echo "   - ❌ DISABLE 'Email each time'"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "2️⃣  CHANGE REPOSITORY WATCH SETTINGS"
echo "   👉 https://github.com/jeremylongshore/hustle"
echo ""
echo "   Actions:"
echo "   - Click 'Watch' button (top right)"
echo "   - Select '⚙️ Custom'"
echo "   - ✅ CHECK 'Participating and @mentions'"
echo "   - ❌ UNCHECK 'Pull requests'"
echo "   - ❌ UNCHECK 'Issues'"
echo "   - Click 'Apply'"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "3️⃣  UNSUBSCRIBE FROM EXISTING PRS (If any open)"
echo "   👉 https://github.com/jeremylongshore/hustle/pulls"
echo ""
echo "   Actions:"
echo "   - Open each Dependabot PR"
echo "   - Click 'Unsubscribe' button (right sidebar)"
echo "   - Or close the PR to stop notifications"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📧 GMAIL FILTER (Optional - Archive Future Emails)"
echo ""
echo "Create Gmail filter:"
echo "   From: notifications@github.com"
echo "   Subject: [jeremylongshore/hustle]"
echo "   Has the words: dependabot"
echo ""
echo "   Actions:"
echo "   - ✅ Skip Inbox (Archive)"
echo "   - ✅ Apply label: GitHub/Dependabot"
echo "   - ✅ Mark as read"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CURRENT STATUS:"
echo "   - dependabot.yml configured ✅ (groups updates weekly)"
echo "   - open-pull-requests-limit: 1 ✅"
echo "   - schedule: weekly (Mondays) ✅"
echo ""
echo "   ⚠️  But you STILL need to change GitHub settings above!"
echo ""
echo "════════════════════════════════════════════════════════════════"
