name: "QA Feature Idea / Improvement"
description: "Use this when you have an idea for a new feature or an improvement to make things easier."
title: "[QA IDEA]: <short summary>"
labels:
  - source:qa-playtest
  - type:feature
  - triage:needed
body:
  - type: markdown
    attributes:
      value: |
        Use this when you think "It would be great if the app could do X" or
        "This would be easier if we changed Y".

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: "Example: 'Easier way to see all players on one screen.'"
      placeholder: "Example: Add a simple summary card for each team."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: "Describe what is hard, slow, or annoying for you right now."
      placeholder: "Example: It takes too many clicks to see all player stats for a team."
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: "Describe the feature or change in your own words."
      placeholder: "Example: A 'Team Overview' page that shows each player with their key stats in a grid."
    validations:
      required: true

  - type: textarea
    id: where
    attributes:
      label: Where should this live in the app?
      description: "If you know, mention which page/menu you imagine this would be on."
      placeholder: "Example: Under the Team menu, as 'Team Overview' next to 'Players'."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - "Must-have – This would make the app much more useful"
        - "Nice-to-have – Helpful but not required"
        - "Just an idea – Sharing in case it's useful"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Anything else we should know?
      description: "Examples from other apps, screenshots, or extra thoughts."
      placeholder: "Example: Another app I use shows this in a simple dashboard. That worked well."
